version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=14mg5l4o6Raz@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-web-db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:14mg5l4o6Raz@@postgres:5432/todo-web-db
      - DB_NAME=todo-web-db
      - DB_USER=postgres
      - DB_PASSWORD=14mg5l4o6Raz@
      - DB_HOST=raz
      - DB_PORT=5432
