# Generated by Django 5.1.1 on 2024-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
